### ISSUE TITLE
docker version can't be switched in RancherOS

### ISSUE THREAD

**Issue by galal-hussein** [galal-hussein/rancher-ha#3]

**Comment by galal-hussein** [comment]
Could fix this using cloud-config:
```
#cloud-config
rancher:
  docker:
    engine: docker-${docker_version}
```
https://github.com/galal-hussein/rancher-ha/commit/a5d7930f1b396768069f3781f2e72fba824f3ca0
